/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import de.hsesslingen.keim.efs.trias.jaxb.ZonedDateTimeAdapter;


/**
 * A location and access to it by individual transport.
 * 
 * <p>Java class for LocationContextStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationContextStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="LocationRef" type="{http://www.vdv.de/trias}LocationRefStructure"/>
 *           &lt;element name="TripLocation" type="{http://www.vdv.de/trias}TripLocationStructure"/>
 *         &lt;/choice>
 *         &lt;element name="DepArrTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IndividualTransportOptions" type="{http://www.vdv.de/trias}IndividualTransportOptionsStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationContextStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "locationRef",
    "tripLocation",
    "depArrTime",
    "individualTransportOptions"
})
public class LocationContextStructure {

    @XmlElement(name = "LocationRef", namespace = "http://www.vdv.de/trias")
    protected LocationRefStructure locationRef;
    @XmlElement(name = "TripLocation", namespace = "http://www.vdv.de/trias")
    protected TripLocationStructure tripLocation;
    @XmlElement(name = "DepArrTime", namespace = "http://www.vdv.de/trias", type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected ZonedDateTime depArrTime;
    @XmlElement(name = "IndividualTransportOptions", namespace = "http://www.vdv.de/trias")
    protected List<IndividualTransportOptionsStructure> individualTransportOptions;

    /**
     * Gets the value of the locationRef property.
     * 
     * @return
     *     possible object is
     *     {@link LocationRefStructure }
     *     
     */
    public LocationRefStructure getLocationRef() {
        return locationRef;
    }

    /**
     * Sets the value of the locationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationRefStructure }
     *     
     */
    public void setLocationRef(LocationRefStructure value) {
        this.locationRef = value;
    }

    /**
     * Gets the value of the tripLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TripLocationStructure }
     *     
     */
    public TripLocationStructure getTripLocation() {
        return tripLocation;
    }

    /**
     * Sets the value of the tripLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TripLocationStructure }
     *     
     */
    public void setTripLocation(TripLocationStructure value) {
        this.tripLocation = value;
    }

    /**
     * Gets the value of the depArrTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getDepArrTime() {
        return depArrTime;
    }

    /**
     * Sets the value of the depArrTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepArrTime(ZonedDateTime value) {
        this.depArrTime = value;
    }

    /**
     * Gets the value of the individualTransportOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the individualTransportOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndividualTransportOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualTransportOptionsStructure }
     * 
     * 
     */
    public List<IndividualTransportOptionsStructure> getIndividualTransportOptions() {
        if (individualTransportOptions == null) {
            individualTransportOptions = new ArrayList<IndividualTransportOptionsStructure>();
        }
        return this.individualTransportOptions;
    }

}
