/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationParamStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationParamStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.vdv.de/trias}LocationDataFilterGroup"/>
 *         &lt;group ref="{http://www.vdv.de/trias}LocationPolicyGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationParamStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "type",
    "usage",
    "ptModes",
    "operatorFilter",
    "localityRef",
    "pointOfInterestFilter",
    "numberOfResults",
    "continueAt",
    "includePtModes"
})
public class LocationParamStructure {

    @XmlElement(name = "Type", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "string")
    protected List<LocationTypeEnumeration> type;
    @XmlElement(name = "Usage", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "string")
    protected LocationUsageEnumeration usage;
    @XmlElement(name = "PtModes", namespace = "http://www.vdv.de/trias")
    protected PtModeFilterStructure ptModes;
    @XmlElement(name = "OperatorFilter", namespace = "http://www.vdv.de/trias")
    protected OperatorFilterStructure operatorFilter;
    @XmlElement(name = "LocalityRef", namespace = "http://www.vdv.de/trias")
    protected List<LocalityRefStructure> localityRef;
    @XmlElement(name = "PointOfInterestFilter", namespace = "http://www.vdv.de/trias")
    protected PointOfInterestFilterStructure pointOfInterestFilter;
    @XmlElement(name = "NumberOfResults", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfResults;
    @XmlElement(name = "ContinueAt", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger continueAt;
    @XmlElement(name = "IncludePtModes", namespace = "http://www.vdv.de/trias", defaultValue = "false")
    protected Boolean includePtModes;

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationTypeEnumeration }
     * 
     * 
     */
    public List<LocationTypeEnumeration> getType() {
        if (type == null) {
            type = new ArrayList<LocationTypeEnumeration>();
        }
        return this.type;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link LocationUsageEnumeration }
     *     
     */
    public LocationUsageEnumeration getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationUsageEnumeration }
     *     
     */
    public void setUsage(LocationUsageEnumeration value) {
        this.usage = value;
    }

    /**
     * Gets the value of the ptModes property.
     * 
     * @return
     *     possible object is
     *     {@link PtModeFilterStructure }
     *     
     */
    public PtModeFilterStructure getPtModes() {
        return ptModes;
    }

    /**
     * Sets the value of the ptModes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtModeFilterStructure }
     *     
     */
    public void setPtModes(PtModeFilterStructure value) {
        this.ptModes = value;
    }

    /**
     * Gets the value of the operatorFilter property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorFilterStructure }
     *     
     */
    public OperatorFilterStructure getOperatorFilter() {
        return operatorFilter;
    }

    /**
     * Sets the value of the operatorFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorFilterStructure }
     *     
     */
    public void setOperatorFilter(OperatorFilterStructure value) {
        this.operatorFilter = value;
    }

    /**
     * Gets the value of the localityRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localityRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalityRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalityRefStructure }
     * 
     * 
     */
    public List<LocalityRefStructure> getLocalityRef() {
        if (localityRef == null) {
            localityRef = new ArrayList<LocalityRefStructure>();
        }
        return this.localityRef;
    }

    /**
     * Gets the value of the pointOfInterestFilter property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfInterestFilterStructure }
     *     
     */
    public PointOfInterestFilterStructure getPointOfInterestFilter() {
        return pointOfInterestFilter;
    }

    /**
     * Sets the value of the pointOfInterestFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfInterestFilterStructure }
     *     
     */
    public void setPointOfInterestFilter(PointOfInterestFilterStructure value) {
        this.pointOfInterestFilter = value;
    }

    /**
     * Gets the value of the numberOfResults property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfResults() {
        return numberOfResults;
    }

    /**
     * Sets the value of the numberOfResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfResults(BigInteger value) {
        this.numberOfResults = value;
    }

    /**
     * Gets the value of the continueAt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContinueAt() {
        return continueAt;
    }

    /**
     * Sets the value of the continueAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContinueAt(BigInteger value) {
        this.continueAt = value;
    }

    /**
     * Gets the value of the includePtModes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludePtModes() {
        return includePtModes;
    }

    /**
     * Sets the value of the includePtModes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludePtModes(Boolean value) {
        this.includePtModes = value;
    }

}
