/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonalisationResponseStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalisationResponseStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorMessage" type="{http://www.vdv.de/trias}ErrorMessageStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="SaveValue" type="{http://www.vdv.de/trias}PersonalisationSaveValueResponseStructure"/>
 *           &lt;element name="RetrieveValue" type="{http://www.vdv.de/trias}PersonalisationRetrieveValueResponseStructure"/>
 *           &lt;element name="DeleteValue" type="{http://www.vdv.de/trias}PersonalisationDeleteValueResponseStructure"/>
 *           &lt;element name="EnumerateValue" type="{http://www.vdv.de/trias}PersonalisationEnumerateValuesResponseStructure"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalisationResponseStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "errorMessage",
    "saveValue",
    "retrieveValue",
    "deleteValue",
    "enumerateValue"
})
public class PersonalisationResponseStructure {

    @XmlElement(name = "ErrorMessage", namespace = "http://www.vdv.de/trias")
    protected List<ErrorMessageStructure> errorMessage;
    @XmlElement(name = "SaveValue", namespace = "http://www.vdv.de/trias")
    protected PersonalisationSaveValueResponseStructure saveValue;
    @XmlElement(name = "RetrieveValue", namespace = "http://www.vdv.de/trias")
    protected PersonalisationRetrieveValueResponseStructure retrieveValue;
    @XmlElement(name = "DeleteValue", namespace = "http://www.vdv.de/trias")
    protected PersonalisationDeleteValueResponseStructure deleteValue;
    @XmlElement(name = "EnumerateValue", namespace = "http://www.vdv.de/trias")
    protected PersonalisationEnumerateValuesResponseStructure enumerateValue;

    /**
     * Gets the value of the errorMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorMessageStructure }
     * 
     * 
     */
    public List<ErrorMessageStructure> getErrorMessage() {
        if (errorMessage == null) {
            errorMessage = new ArrayList<ErrorMessageStructure>();
        }
        return this.errorMessage;
    }

    /**
     * Gets the value of the saveValue property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalisationSaveValueResponseStructure }
     *     
     */
    public PersonalisationSaveValueResponseStructure getSaveValue() {
        return saveValue;
    }

    /**
     * Sets the value of the saveValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalisationSaveValueResponseStructure }
     *     
     */
    public void setSaveValue(PersonalisationSaveValueResponseStructure value) {
        this.saveValue = value;
    }

    /**
     * Gets the value of the retrieveValue property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalisationRetrieveValueResponseStructure }
     *     
     */
    public PersonalisationRetrieveValueResponseStructure getRetrieveValue() {
        return retrieveValue;
    }

    /**
     * Sets the value of the retrieveValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalisationRetrieveValueResponseStructure }
     *     
     */
    public void setRetrieveValue(PersonalisationRetrieveValueResponseStructure value) {
        this.retrieveValue = value;
    }

    /**
     * Gets the value of the deleteValue property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalisationDeleteValueResponseStructure }
     *     
     */
    public PersonalisationDeleteValueResponseStructure getDeleteValue() {
        return deleteValue;
    }

    /**
     * Sets the value of the deleteValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalisationDeleteValueResponseStructure }
     *     
     */
    public void setDeleteValue(PersonalisationDeleteValueResponseStructure value) {
        this.deleteValue = value;
    }

    /**
     * Gets the value of the enumerateValue property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalisationEnumerateValuesResponseStructure }
     *     
     */
    public PersonalisationEnumerateValuesResponseStructure getEnumerateValue() {
        return enumerateValue;
    }

    /**
     * Sets the value of the enumerateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalisationEnumerateValuesResponseStructure }
     *     
     */
    public void setEnumerateValue(PersonalisationEnumerateValuesResponseStructure value) {
        this.enumerateValue = value;
    }

}
