/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


import lombok.ToString;
@ToString
/**
 * List of public transport modes to include or exclude.
 * 
 * <p>Java class for PtModeFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PtModeFilterStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Exclude" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PtMode" type="{http://www.vdv.de/trias}PtModesEnumeration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.vdv.de/trias}PtSubmodeChoiceGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PtModeFilterStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "exclude",
    "ptMode",
    "ptSubmodeChoiceGroup"
})
public class PtModeFilter {

    @XmlElement(name = "Exclude", namespace = "http://www.vdv.de/trias", defaultValue = "true")
    protected Boolean exclude;
    @XmlElement(name = "PtMode", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "NMTOKEN")
    protected List<PtModesEnumeration> ptMode;
    @XmlElements({
        @XmlElement(name = "AirSubmode", namespace = "http://www.vdv.de/trias", type = AirSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "BusSubmode", namespace = "http://www.vdv.de/trias", type = BusSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "CoachSubmode", namespace = "http://www.vdv.de/trias", type = CoachSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "FunicularSubmode", namespace = "http://www.vdv.de/trias", type = FunicularSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "MetroSubmode", namespace = "http://www.vdv.de/trias", type = MetroSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "RailSubmode", namespace = "http://www.vdv.de/trias", type = RailSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "TelecabinSubmode", namespace = "http://www.vdv.de/trias", type = TelecabinSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "TramSubmode", namespace = "http://www.vdv.de/trias", type = TramSubmodeEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "WaterSubmode", namespace = "http://www.vdv.de/trias", type = WaterSubmodeEnumeration.class, defaultValue = "unknown")
    })
    protected List<Object> ptSubmodeChoiceGroup;

    /**
     * Gets the value of the exclude property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExclude() {
        return exclude;
    }

    /**
     * Sets the value of the exclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public PtModeFilter setExclude(Boolean value) {
        this.exclude = value;
        return this;
    }

    /**
     * Gets the value of the ptMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PtModesEnumeration }
     * 
     * 
     */
    public List<PtModesEnumeration> getPtMode() {
        if (ptMode == null) {
            ptMode = new ArrayList<PtModesEnumeration>();
        }
        return this.ptMode;
    }

    /**
     * Gets the value of the ptSubmodeChoiceGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptSubmodeChoiceGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtSubmodeChoiceGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirSubmodeEnumeration }
     * {@link BusSubmodeEnumeration }
     * {@link CoachSubmodeEnumeration }
     * {@link FunicularSubmodeEnumeration }
     * {@link MetroSubmodeEnumeration }
     * {@link RailSubmodeEnumeration }
     * {@link TelecabinSubmodeEnumeration }
     * {@link TramSubmodeEnumeration }
     * {@link WaterSubmodeEnumeration }
     * 
     * 
     */
    public List<Object> getPtSubmodeChoiceGroup() {
        if (ptSubmodeChoiceGroup == null) {
            ptSubmodeChoiceGroup = new ArrayList<Object>();
        }
        return this.ptSubmodeChoiceGroup;
    }

}
