/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Request to register a service.
 * 
 * <p>Java class for ServiceRegisterRegisterRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRegisterRegisterRequestStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.vdv.de/trias}TriasServicePropertiesGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRegisterRegisterRequestStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "serviceType",
    "version",
    "serviceAddress",
    "participantRef",
    "serviceUsage"
})
public class ServiceRegisterRegisterRequest {

    @XmlElement(name = "ServiceType", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "string")
    protected TriasServiceTypeEnumeration serviceType;
    @XmlElement(name = "Version", namespace = "http://www.vdv.de/trias")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String version;
    @XmlElement(name = "ServiceAddress", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "anyURI")
    protected String serviceAddress;
    @XmlElement(name = "ParticipantRef", namespace = "http://www.vdv.de/trias")
    protected ParticipantRef participantRef;
    @XmlElement(name = "ServiceUsage", namespace = "http://www.vdv.de/trias", defaultValue = "Provider")
    @XmlSchemaType(name = "string")
    protected ServiceUsageEnumeration serviceUsage;

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link TriasServiceTypeEnumeration }
     *     
     */
    public TriasServiceTypeEnumeration getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriasServiceTypeEnumeration }
     *     
     */
    public ServiceRegisterRegisterRequest setServiceType(TriasServiceTypeEnumeration value) {
        this.serviceType = value;
        return this;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public ServiceRegisterRegisterRequest setVersion(String value) {
        this.version = value;
        return this;
    }

    /**
     * Gets the value of the serviceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Sets the value of the serviceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public ServiceRegisterRegisterRequest setServiceAddress(String value) {
        this.serviceAddress = value;
        return this;
    }

    /**
     * Gets the value of the participantRef property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantRef }
     *     
     */
    public ParticipantRef getParticipantRef() {
        return participantRef;
    }

    /**
     * Sets the value of the participantRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantRef }
     *     
     */
    public ServiceRegisterRegisterRequest setParticipantRef(ParticipantRef value) {
        this.participantRef = value;
        return this;
    }

    /**
     * Gets the value of the serviceUsage property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceUsageEnumeration }
     *     
     */
    public ServiceUsageEnumeration getServiceUsage() {
        return serviceUsage;
    }

    /**
     * Sets the value of the serviceUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceUsageEnumeration }
     *     
     */
    public ServiceRegisterRegisterRequest setServiceUsage(ServiceUsageEnumeration value) {
        this.serviceUsage = value;
        return this;
    }

}
