/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Service register result structure.
 * 
 * <p>Java class for ServiceRegisterResultStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRegisterResultStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResultId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *         &lt;element name="ErrorMessage" type="{http://www.vdv.de/trias}ErrorMessageStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="RegisterResponse" type="{http://www.vdv.de/trias}ServiceRegisterRegisterResponseStructure"/>
 *           &lt;element name="UpdateResponse" type="{http://www.vdv.de/trias}ServiceRegisterUpdateResponseStructure"/>
 *           &lt;element name="LookupResponse" type="{http://www.vdv.de/trias}ServiceRegisterLookupResponseStructure"/>
 *           &lt;element name="UnregisterResponse" type="{http://www.vdv.de/trias}ServiceRegisterUnregisterResponseStructure"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRegisterResultStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "resultId",
    "errorMessage",
    "registerResponse",
    "updateResponse",
    "lookupResponse",
    "unregisterResponse"
})
public class ServiceRegisterResultStructure {

    @XmlElement(name = "ResultId", namespace = "http://www.vdv.de/trias", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resultId;
    @XmlElement(name = "ErrorMessage", namespace = "http://www.vdv.de/trias")
    protected List<ErrorMessageStructure> errorMessage;
    @XmlElement(name = "RegisterResponse", namespace = "http://www.vdv.de/trias")
    protected ServiceRegisterRegisterResponseStructure registerResponse;
    @XmlElement(name = "UpdateResponse", namespace = "http://www.vdv.de/trias")
    protected ServiceRegisterUpdateResponseStructure updateResponse;
    @XmlElement(name = "LookupResponse", namespace = "http://www.vdv.de/trias")
    protected ServiceRegisterLookupResponseStructure lookupResponse;
    @XmlElement(name = "UnregisterResponse", namespace = "http://www.vdv.de/trias")
    protected ServiceRegisterUnregisterResponseStructure unregisterResponse;

    /**
     * Gets the value of the resultId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultId() {
        return resultId;
    }

    /**
     * Sets the value of the resultId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultId(String value) {
        this.resultId = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorMessageStructure }
     * 
     * 
     */
    public List<ErrorMessageStructure> getErrorMessage() {
        if (errorMessage == null) {
            errorMessage = new ArrayList<ErrorMessageStructure>();
        }
        return this.errorMessage;
    }

    /**
     * Gets the value of the registerResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRegisterRegisterResponseStructure }
     *     
     */
    public ServiceRegisterRegisterResponseStructure getRegisterResponse() {
        return registerResponse;
    }

    /**
     * Sets the value of the registerResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRegisterRegisterResponseStructure }
     *     
     */
    public void setRegisterResponse(ServiceRegisterRegisterResponseStructure value) {
        this.registerResponse = value;
    }

    /**
     * Gets the value of the updateResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRegisterUpdateResponseStructure }
     *     
     */
    public ServiceRegisterUpdateResponseStructure getUpdateResponse() {
        return updateResponse;
    }

    /**
     * Sets the value of the updateResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRegisterUpdateResponseStructure }
     *     
     */
    public void setUpdateResponse(ServiceRegisterUpdateResponseStructure value) {
        this.updateResponse = value;
    }

    /**
     * Gets the value of the lookupResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRegisterLookupResponseStructure }
     *     
     */
    public ServiceRegisterLookupResponseStructure getLookupResponse() {
        return lookupResponse;
    }

    /**
     * Sets the value of the lookupResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRegisterLookupResponseStructure }
     *     
     */
    public void setLookupResponse(ServiceRegisterLookupResponseStructure value) {
        this.lookupResponse = value;
    }

    /**
     * Gets the value of the unregisterResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRegisterUnregisterResponseStructure }
     *     
     */
    public ServiceRegisterUnregisterResponseStructure getUnregisterResponse() {
        return unregisterResponse;
    }

    /**
     * Sets the value of the unregisterResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRegisterUnregisterResponseStructure }
     *     
     */
    public void setUnregisterResponse(ServiceRegisterUnregisterResponseStructure value) {
        this.unregisterResponse = value;
    }

}
