/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * Request specific parameters
 * 
 * <p>Java class for StopEventParamStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopEventParamStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.vdv.de/trias}StopEventDataFilterGroup"/>
 *         &lt;group ref="{http://www.vdv.de/trias}StopEventPolicyGroup"/>
 *         &lt;group ref="{http://www.vdv.de/trias}StopEventContentFilterGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopEventParamStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "ptModeFilter",
    "lineFilter",
    "operatorFilter",
    "numberOfResults",
    "timeWindow",
    "stopEventType",
    "includePreviousCalls",
    "includeOnwardCalls",
    "includeOperatingDays",
    "includeRealtimeData"
})
public class StopEventParamStructure {

    @XmlElement(name = "PtModeFilter", namespace = "http://www.vdv.de/trias")
    protected PtModeFilterStructure ptModeFilter;
    @XmlElement(name = "LineFilter", namespace = "http://www.vdv.de/trias")
    protected LineDirectionFilterStructure lineFilter;
    @XmlElement(name = "OperatorFilter", namespace = "http://www.vdv.de/trias")
    protected OperatorFilterStructure operatorFilter;
    @XmlElement(name = "NumberOfResults", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfResults;
    @XmlElement(name = "TimeWindow", namespace = "http://www.vdv.de/trias")
    protected Duration timeWindow;
    @XmlElement(name = "StopEventType", namespace = "http://www.vdv.de/trias", defaultValue = "departure")
    @XmlSchemaType(name = "string")
    protected StopEventTypeEnumeration stopEventType;
    @XmlElement(name = "IncludePreviousCalls", namespace = "http://www.vdv.de/trias", defaultValue = "false")
    protected Boolean includePreviousCalls;
    @XmlElement(name = "IncludeOnwardCalls", namespace = "http://www.vdv.de/trias", defaultValue = "false")
    protected Boolean includeOnwardCalls;
    @XmlElement(name = "IncludeOperatingDays", namespace = "http://www.vdv.de/trias", defaultValue = "false")
    protected Boolean includeOperatingDays;
    @XmlElement(name = "IncludeRealtimeData", namespace = "http://www.vdv.de/trias", defaultValue = "false")
    protected Boolean includeRealtimeData;

    /**
     * Gets the value of the ptModeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link PtModeFilterStructure }
     *     
     */
    public PtModeFilterStructure getPtModeFilter() {
        return ptModeFilter;
    }

    /**
     * Sets the value of the ptModeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtModeFilterStructure }
     *     
     */
    public void setPtModeFilter(PtModeFilterStructure value) {
        this.ptModeFilter = value;
    }

    /**
     * Gets the value of the lineFilter property.
     * 
     * @return
     *     possible object is
     *     {@link LineDirectionFilterStructure }
     *     
     */
    public LineDirectionFilterStructure getLineFilter() {
        return lineFilter;
    }

    /**
     * Sets the value of the lineFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineDirectionFilterStructure }
     *     
     */
    public void setLineFilter(LineDirectionFilterStructure value) {
        this.lineFilter = value;
    }

    /**
     * Gets the value of the operatorFilter property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorFilterStructure }
     *     
     */
    public OperatorFilterStructure getOperatorFilter() {
        return operatorFilter;
    }

    /**
     * Sets the value of the operatorFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorFilterStructure }
     *     
     */
    public void setOperatorFilter(OperatorFilterStructure value) {
        this.operatorFilter = value;
    }

    /**
     * Gets the value of the numberOfResults property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfResults() {
        return numberOfResults;
    }

    /**
     * Sets the value of the numberOfResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfResults(BigInteger value) {
        this.numberOfResults = value;
    }

    /**
     * Gets the value of the timeWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTimeWindow() {
        return timeWindow;
    }

    /**
     * Sets the value of the timeWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTimeWindow(Duration value) {
        this.timeWindow = value;
    }

    /**
     * Gets the value of the stopEventType property.
     * 
     * @return
     *     possible object is
     *     {@link StopEventTypeEnumeration }
     *     
     */
    public StopEventTypeEnumeration getStopEventType() {
        return stopEventType;
    }

    /**
     * Sets the value of the stopEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopEventTypeEnumeration }
     *     
     */
    public void setStopEventType(StopEventTypeEnumeration value) {
        this.stopEventType = value;
    }

    /**
     * Gets the value of the includePreviousCalls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludePreviousCalls() {
        return includePreviousCalls;
    }

    /**
     * Sets the value of the includePreviousCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludePreviousCalls(Boolean value) {
        this.includePreviousCalls = value;
    }

    /**
     * Gets the value of the includeOnwardCalls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeOnwardCalls() {
        return includeOnwardCalls;
    }

    /**
     * Sets the value of the includeOnwardCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeOnwardCalls(Boolean value) {
        this.includeOnwardCalls = value;
    }

    /**
     * Gets the value of the includeOperatingDays property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeOperatingDays() {
        return includeOperatingDays;
    }

    /**
     * Sets the value of the includeOperatingDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeOperatingDays(Boolean value) {
        this.includeOperatingDays = value;
    }

    /**
     * Gets the value of the includeRealtimeData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeRealtimeData() {
        return includeRealtimeData;
    }

    /**
     * Sets the value of the includeRealtimeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeRealtimeData(Boolean value) {
        this.includeRealtimeData = value;
    }

}
