/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * A piece of a trip. A trip leg.may consist of multiple TrackSections. Describes the geographic embedding.
 * 
 * <p>Java class for TrackSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackSectionStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrackStart" type="{http://www.vdv.de/trias}LocationRefStructure" minOccurs="0"/>
 *         &lt;element name="TrackEnd" type="{http://www.vdv.de/trias}LocationRefStructure" minOccurs="0"/>
 *         &lt;element name="Projection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://www.vdv.de/trias}GeoPositionStructure" maxOccurs="unbounded" minOccurs="2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoadName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="Length" type="{http://www.vdv.de/trias}DistanceType" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackSectionStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "trackStart",
    "trackEnd",
    "projection",
    "roadName",
    "duration",
    "length",
    "extension"
})
public class TrackSection {

    @XmlElement(name = "TrackStart", namespace = "http://www.vdv.de/trias")
    protected LocationRef trackStart;
    @XmlElement(name = "TrackEnd", namespace = "http://www.vdv.de/trias")
    protected LocationRef trackEnd;
    @XmlElement(name = "Projection", namespace = "http://www.vdv.de/trias")
    protected TrackSection.Projection projection;
    @XmlElement(name = "RoadName", namespace = "http://www.vdv.de/trias")
    protected String roadName;
    @XmlElement(name = "Duration", namespace = "http://www.vdv.de/trias")
    protected Duration duration;
    @XmlElement(name = "Length", namespace = "http://www.vdv.de/trias")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger length;
    @XmlElement(name = "Extension", namespace = "http://www.vdv.de/trias")
    protected Object extension;

    /**
     * Gets the value of the trackStart property.
     * 
     * @return
     *     possible object is
     *     {@link LocationRef }
     *     
     */
    public LocationRef getTrackStart() {
        return trackStart;
    }

    /**
     * Sets the value of the trackStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationRef }
     *     
     */
    public TrackSection setTrackStart(LocationRef value) {
        this.trackStart = value;
        return this;
    }

    /**
     * Gets the value of the trackEnd property.
     * 
     * @return
     *     possible object is
     *     {@link LocationRef }
     *     
     */
    public LocationRef getTrackEnd() {
        return trackEnd;
    }

    /**
     * Sets the value of the trackEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationRef }
     *     
     */
    public TrackSection setTrackEnd(LocationRef value) {
        this.trackEnd = value;
        return this;
    }

    /**
     * Gets the value of the projection property.
     * 
     * @return
     *     possible object is
     *     {@link TrackSection.Projection }
     *     
     */
    public TrackSection.Projection getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackSection.Projection }
     *     
     */
    public void setProjection(TrackSection.Projection value) {
        this.projection = value;
    }

    /**
     * Gets the value of the roadName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * Sets the value of the roadName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public TrackSection setRoadName(String value) {
        this.roadName = value;
        return this;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public TrackSection setDuration(Duration value) {
        this.duration = value;
        return this;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public TrackSection setLength(BigInteger value) {
        this.length = value;
        return this;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public TrackSection setExtension(Object value) {
        this.extension = value;
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://www.vdv.de/trias}GeoPositionStructure" maxOccurs="unbounded" minOccurs="2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class Projection {

        @XmlElement(name = "Position", namespace = "http://www.vdv.de/trias", required = true)
        protected List<GeoPosition> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeoPosition }
         * 
         * 
         */
        public List<GeoPosition> getPosition() {
            if (position == null) {
                position = new ArrayList<GeoPosition>();
            }
            return this.position;
        }

    }

}
