/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.vdv.trias;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import de.hsesslingen.keim.efs.adapter.trias.jaxb.ZonedDateTimeAdapter;


import lombok.ToString;
@ToString
/**
 * TripInfo request structure.
 * 
 * <p>Java class for TripInfoRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TripInfoRequestStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;group ref="{http://www.vdv.de/trias}DatedJourneyRefGroup"/>
 *           &lt;group ref="{http://www.vdv.de/trias}TimedVehicleRefGroup"/>
 *         &lt;/choice>
 *         &lt;element name="Params" type="{http://www.vdv.de/trias}TripInfoParamStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TripInfoRequestStructure", namespace = "http://www.vdv.de/trias", propOrder = {
    "journeyRef",
    "operatingDayRef",
    "vehicleRef",
    "timeOfOperation",
    "params"
})
public class TripInfoRequest {

    @XmlElement(name = "JourneyRef", namespace = "http://www.vdv.de/trias")
    protected JourneyRef journeyRef;
    @XmlElement(name = "OperatingDayRef", namespace = "http://www.vdv.de/trias")
    protected OperatingDayRef operatingDayRef;
    @XmlElement(name = "VehicleRef", namespace = "http://www.vdv.de/trias")
    protected VehicleRef vehicleRef;
    @XmlElement(name = "TimeOfOperation", namespace = "http://www.vdv.de/trias", type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected ZonedDateTime timeOfOperation;
    @XmlElement(name = "Params", namespace = "http://www.vdv.de/trias")
    protected TripInfoParam params;

    /**
     * Gets the value of the journeyRef property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyRef }
     *     
     */
    public JourneyRef getJourneyRef() {
        return journeyRef;
    }

    /**
     * Sets the value of the journeyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyRef }
     *     
     */
    public TripInfoRequest setJourneyRef(JourneyRef value) {
        this.journeyRef = value;
        return this;
    }

    /**
     * Gets the value of the operatingDayRef property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingDayRef }
     *     
     */
    public OperatingDayRef getOperatingDayRef() {
        return operatingDayRef;
    }

    /**
     * Sets the value of the operatingDayRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingDayRef }
     *     
     */
    public TripInfoRequest setOperatingDayRef(OperatingDayRef value) {
        this.operatingDayRef = value;
        return this;
    }

    /**
     * Gets the value of the vehicleRef property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleRef }
     *     
     */
    public VehicleRef getVehicleRef() {
        return vehicleRef;
    }

    /**
     * Sets the value of the vehicleRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleRef }
     *     
     */
    public TripInfoRequest setVehicleRef(VehicleRef value) {
        this.vehicleRef = value;
        return this;
    }

    /**
     * Gets the value of the timeOfOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getTimeOfOperation() {
        return timeOfOperation;
    }

    /**
     * Sets the value of the timeOfOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public TripInfoRequest setTimeOfOperation(ZonedDateTime value) {
        this.timeOfOperation = value;
        return this;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link TripInfoParam }
     *     
     */
    public TripInfoParam getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link TripInfoParam }
     *     
     */
    public TripInfoRequest setParams(TripInfoParam value) {
        this.params = value;
        return this;
    }

}
