/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package eu.datex2.schema._1_0._1_0;

import lombok.ToString;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A linear section along a road with optional directionality defined between two points on the road. 
 * 
 * <p>Java class for Linear complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Linear">
 *   &lt;complexContent>
 *     &lt;extension base="{http://datex2.eu/schema/1_0/1_0}NetworkLocation">
 *       &lt;sequence>
 *         &lt;element name="tpeglinearLocation" type="{http://datex2.eu/schema/1_0/1_0}TPEGLinearLocation" minOccurs="0"/>
 *         &lt;element name="alertCLinear" type="{http://datex2.eu/schema/1_0/1_0}AlertCLinear" minOccurs="0"/>
 *         &lt;element name="referencePointLinear" type="{http://datex2.eu/schema/1_0/1_0}ReferencePointLinear" minOccurs="0"/>
 *         &lt;element name="linearExtension" type="{http://datex2.eu/schema/1_0/1_0}ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Linear", namespace = "http://datex2.eu/schema/1_0/1_0", propOrder = {
    "tpeglinearLocation",
    "alertCLinear",
    "referencePointLinear",
    "linearExtension"
})
@ToString
public class Linear
    extends NetworkLocation
{

    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected TPEGLinearLocation tpeglinearLocation;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected AlertCLinear alertCLinear;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected ReferencePointLinear referencePointLinear;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected ExtensionType linearExtension;

    /**
     * Gets the value of the tpeglinearLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TPEGLinearLocation }
     *     
     */
    public TPEGLinearLocation getTpeglinearLocation() {
        return tpeglinearLocation;
    }

    /**
     * Sets the value of the tpeglinearLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPEGLinearLocation }
     *     
     */
    public Linear setTpeglinearLocation(TPEGLinearLocation value) {
        this.tpeglinearLocation = value;
        return this;
    }

    /**
     * Gets the value of the alertCLinear property.
     * 
     * @return
     *     possible object is
     *     {@link AlertCLinear }
     *     
     */
    public AlertCLinear getAlertCLinear() {
        return alertCLinear;
    }

    /**
     * Sets the value of the alertCLinear property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertCLinear }
     *     
     */
    public Linear setAlertCLinear(AlertCLinear value) {
        this.alertCLinear = value;
        return this;
    }

    /**
     * Gets the value of the referencePointLinear property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePointLinear }
     *     
     */
    public ReferencePointLinear getReferencePointLinear() {
        return referencePointLinear;
    }

    /**
     * Sets the value of the referencePointLinear property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePointLinear }
     *     
     */
    public Linear setReferencePointLinear(ReferencePointLinear value) {
        this.referencePointLinear = value;
        return this;
    }

    /**
     * Gets the value of the linearExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getLinearExtension() {
        return linearExtension;
    }

    /**
     * Sets the value of the linearExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public Linear setLinearExtension(ExtensionType value) {
        this.linearExtension = value;
        return this;
    }

}
