/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package eu.datex2.schema._1_0._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A single geospatial point.
 * 
 * <p>Java class for Point complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Point">
 *   &lt;complexContent>
 *     &lt;extension base="{http://datex2.eu/schema/1_0/1_0}NetworkLocation">
 *       &lt;sequence>
 *         &lt;element name="tpegpointLocation" type="{http://datex2.eu/schema/1_0/1_0}TPEGPointLocation" minOccurs="0"/>
 *         &lt;element name="alertCPoint" type="{http://datex2.eu/schema/1_0/1_0}AlertCPoint" minOccurs="0"/>
 *         &lt;element name="referencePoint" type="{http://datex2.eu/schema/1_0/1_0}ReferencePoint" minOccurs="0"/>
 *         &lt;element name="pointByCoordinates" type="{http://datex2.eu/schema/1_0/1_0}PointByCoordinates" minOccurs="0"/>
 *         &lt;element name="pointExtension" type="{http://datex2.eu/schema/1_0/1_0}ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Point", namespace = "http://datex2.eu/schema/1_0/1_0", propOrder = {
    "tpegpointLocation",
    "alertCPoint",
    "referencePoint",
    "pointByCoordinates",
    "pointExtension"
})
public class Point
    extends NetworkLocation
{

    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected TPEGPointLocation tpegpointLocation;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected AlertCPoint alertCPoint;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected ReferencePoint referencePoint;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected PointByCoordinates pointByCoordinates;
    @XmlElement(namespace = "http://datex2.eu/schema/1_0/1_0")
    protected ExtensionType pointExtension;

    /**
     * Gets the value of the tpegpointLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TPEGPointLocation }
     *     
     */
    public TPEGPointLocation getTpegpointLocation() {
        return tpegpointLocation;
    }

    /**
     * Sets the value of the tpegpointLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPEGPointLocation }
     *     
     */
    public void setTpegpointLocation(TPEGPointLocation value) {
        this.tpegpointLocation = value;
    }

    /**
     * Gets the value of the alertCPoint property.
     * 
     * @return
     *     possible object is
     *     {@link AlertCPoint }
     *     
     */
    public AlertCPoint getAlertCPoint() {
        return alertCPoint;
    }

    /**
     * Sets the value of the alertCPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertCPoint }
     *     
     */
    public void setAlertCPoint(AlertCPoint value) {
        this.alertCPoint = value;
    }

    /**
     * Gets the value of the referencePoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint }
     *     
     */
    public ReferencePoint getReferencePoint() {
        return referencePoint;
    }

    /**
     * Sets the value of the referencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint }
     *     
     */
    public void setReferencePoint(ReferencePoint value) {
        this.referencePoint = value;
    }

    /**
     * Gets the value of the pointByCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link PointByCoordinates }
     *     
     */
    public PointByCoordinates getPointByCoordinates() {
        return pointByCoordinates;
    }

    /**
     * Sets the value of the pointByCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointByCoordinates }
     *     
     */
    public void setPointByCoordinates(PointByCoordinates value) {
        this.pointByCoordinates = value;
    }

    /**
     * Gets the value of the pointExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getPointExtension() {
        return pointExtension;
    }

    /**
     * Sets the value of the pointExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setPointExtension(ExtensionType value) {
        this.pointExtension = value;
    }

}
