/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


import lombok.ToString;
@ToString
/**
 * Type for an interchange Activity.
 * 
 * <p>Java class for AbstractDistributorItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDistributorItemStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/siri}AbstractItemStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.siri.org.uk/siri}InterchangeDistributorIdentityGroup"/>
 *         &lt;element name="DistributorJourney" type="{http://www.siri.org.uk/siri}InterchangeJourneyStructure"/>
 *         &lt;element name="FeederVehicleJourneyRef" type="{http://www.siri.org.uk/siri}FramedVehicleJourneyRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDistributorItemStructure", namespace = "http://www.siri.org.uk/siri", propOrder = {
    "interchangeRef",
    "connectionLinkRef",
    "stopPointRef",
    "distributorVisitNumber",
    "distributorOrder",
    "distributorJourney",
    "feederVehicleJourneyRef"
})
@XmlSeeAlso({
    WaitProlongedDeparture.class,
    StoppingPositionChangedDeparture.class,
    DistributorDepartureCancellation.class
})
public class AbstractDistributorItem
    extends AbstractItem
{

    @XmlElement(name = "InterchangeRef", namespace = "http://www.siri.org.uk/siri")
    protected InterchangeRef interchangeRef;
    @XmlElement(name = "ConnectionLinkRef", namespace = "http://www.siri.org.uk/siri", required = true)
    protected ConnectionLinkRef connectionLinkRef;
    @XmlElement(name = "StopPointRef", namespace = "http://www.siri.org.uk/siri")
    protected StopPointRef stopPointRef;
    @XmlElement(name = "DistributorVisitNumber", namespace = "http://www.siri.org.uk/siri")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger distributorVisitNumber;
    @XmlElement(name = "DistributorOrder", namespace = "http://www.siri.org.uk/siri")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger distributorOrder;
    @XmlElement(name = "DistributorJourney", namespace = "http://www.siri.org.uk/siri", required = true)
    protected InterchangeJourney distributorJourney;
    @XmlElement(name = "FeederVehicleJourneyRef", namespace = "http://www.siri.org.uk/siri")
    protected List<FramedVehicleJourneyRef> feederVehicleJourneyRef;

    /**
     * Gets the value of the interchangeRef property.
     * 
     * @return
     *     possible object is
     *     {@link InterchangeRef }
     *     
     */
    public InterchangeRef getInterchangeRef() {
        return interchangeRef;
    }

    /**
     * Sets the value of the interchangeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterchangeRef }
     *     
     */
    public AbstractDistributorItem setInterchangeRef(InterchangeRef value) {
        this.interchangeRef = value;
        return this;
    }

    /**
     * Gets the value of the connectionLinkRef property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionLinkRef }
     *     
     */
    public ConnectionLinkRef getConnectionLinkRef() {
        return connectionLinkRef;
    }

    /**
     * Sets the value of the connectionLinkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionLinkRef }
     *     
     */
    public AbstractDistributorItem setConnectionLinkRef(ConnectionLinkRef value) {
        this.connectionLinkRef = value;
        return this;
    }

    /**
     * Gets the value of the stopPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link StopPointRef }
     *     
     */
    public StopPointRef getStopPointRef() {
        return stopPointRef;
    }

    /**
     * Sets the value of the stopPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPointRef }
     *     
     */
    public AbstractDistributorItem setStopPointRef(StopPointRef value) {
        this.stopPointRef = value;
        return this;
    }

    /**
     * Gets the value of the distributorVisitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistributorVisitNumber() {
        return distributorVisitNumber;
    }

    /**
     * Sets the value of the distributorVisitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public AbstractDistributorItem setDistributorVisitNumber(BigInteger value) {
        this.distributorVisitNumber = value;
        return this;
    }

    /**
     * Gets the value of the distributorOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistributorOrder() {
        return distributorOrder;
    }

    /**
     * Sets the value of the distributorOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public AbstractDistributorItem setDistributorOrder(BigInteger value) {
        this.distributorOrder = value;
        return this;
    }

    /**
     * Gets the value of the distributorJourney property.
     * 
     * @return
     *     possible object is
     *     {@link InterchangeJourney }
     *     
     */
    public InterchangeJourney getDistributorJourney() {
        return distributorJourney;
    }

    /**
     * Sets the value of the distributorJourney property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterchangeJourney }
     *     
     */
    public AbstractDistributorItem setDistributorJourney(InterchangeJourney value) {
        this.distributorJourney = value;
        return this;
    }

    /**
     * Gets the value of the feederVehicleJourneyRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feederVehicleJourneyRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeederVehicleJourneyRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FramedVehicleJourneyRef }
     * 
     * 
     */
    public List<FramedVehicleJourneyRef> getFeederVehicleJourneyRef() {
        if (feederVehicleJourneyRef == null) {
            feederVehicleJourneyRef = new ArrayList<FramedVehicleJourneyRef>();
        }
        return this.feederVehicleJourneyRef;
    }

}
