/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FareClassFacilityEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FareClassFacilityEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="pti23_0"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="pti23_6"/>
 *     &lt;enumeration value="firstClass"/>
 *     &lt;enumeration value="pti23_7"/>
 *     &lt;enumeration value="secondClass"/>
 *     &lt;enumeration value="pti23_8"/>
 *     &lt;enumeration value="thirdClass"/>
 *     &lt;enumeration value="pti23_9"/>
 *     &lt;enumeration value="economyClass"/>
 *     &lt;enumeration value="pti23_10"/>
 *     &lt;enumeration value="businessClass"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FareClassFacilityEnumeration", namespace = "http://www.siri.org.uk/siri")
@XmlEnum
public enum FareClassFacilityEnumeration {

    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("pti23_0")
    PTI_23_0("pti23_0"),
    @XmlEnumValue("pti23_6")
    PTI_23_6("pti23_6"),
    @XmlEnumValue("firstClass")
    FIRST_CLASS("firstClass"),
    @XmlEnumValue("pti23_7")
    PTI_23_7("pti23_7"),
    @XmlEnumValue("secondClass")
    SECOND_CLASS("secondClass"),
    @XmlEnumValue("pti23_8")
    PTI_23_8("pti23_8"),
    @XmlEnumValue("thirdClass")
    THIRD_CLASS("thirdClass"),
    @XmlEnumValue("pti23_9")
    PTI_23_9("pti23_9"),
    @XmlEnumValue("economyClass")
    ECONOMY_CLASS("economyClass"),
    @XmlEnumValue("pti23_10")
    PTI_23_10("pti23_10"),
    @XmlEnumValue("businessClass")
    BUSINESS_CLASS("businessClass");
    private final String value;

    FareClassFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FareClassFacilityEnumeration fromValue(String v) {
        for (FareClassFacilityEnumeration c: FareClassFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
