/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HolidayTypeEnumerationx.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HolidayTypeEnumerationx">
 *   &lt;restriction base="{http://www.siri.org.uk/siri}DayTypeEnumeration">
 *     &lt;enumeration value="holiday"/>
 *     &lt;enumeration value="publicHoliday"/>
 *     &lt;enumeration value="religiousHoliday"/>
 *     &lt;enumeration value="federalHoliday"/>
 *     &lt;enumeration value="regionalHoliday"/>
 *     &lt;enumeration value="nationalHoliday"/>
 *     &lt;enumeration value="sundaysAndPublicHolidays"/>
 *     &lt;enumeration value="schoolDays"/>
 *     &lt;enumeration value="everyDay"/>
 *     &lt;enumeration value="undefinedDayType"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HolidayTypeEnumerationx", namespace = "http://www.siri.org.uk/siri")
@XmlEnum(DayTypeEnumeration.class)
public enum HolidayTypeEnumerationx {

    @XmlEnumValue("holiday")
    HOLIDAY(DayTypeEnumeration.HOLIDAY),
    @XmlEnumValue("publicHoliday")
    PUBLIC_HOLIDAY(DayTypeEnumeration.PUBLIC_HOLIDAY),
    @XmlEnumValue("religiousHoliday")
    RELIGIOUS_HOLIDAY(DayTypeEnumeration.RELIGIOUS_HOLIDAY),
    @XmlEnumValue("federalHoliday")
    FEDERAL_HOLIDAY(DayTypeEnumeration.FEDERAL_HOLIDAY),
    @XmlEnumValue("regionalHoliday")
    REGIONAL_HOLIDAY(DayTypeEnumeration.REGIONAL_HOLIDAY),
    @XmlEnumValue("nationalHoliday")
    NATIONAL_HOLIDAY(DayTypeEnumeration.NATIONAL_HOLIDAY),
    @XmlEnumValue("sundaysAndPublicHolidays")
    SUNDAYS_AND_PUBLIC_HOLIDAYS(DayTypeEnumeration.SUNDAYS_AND_PUBLIC_HOLIDAYS),
    @XmlEnumValue("schoolDays")
    SCHOOL_DAYS(DayTypeEnumeration.SCHOOL_DAYS),
    @XmlEnumValue("everyDay")
    EVERY_DAY(DayTypeEnumeration.EVERY_DAY),
    @XmlEnumValue("undefinedDayType")
    UNDEFINED_DAY_TYPE(DayTypeEnumeration.UNDEFINED_DAY_TYPE);
    private final DayTypeEnumeration value;

    HolidayTypeEnumerationx(DayTypeEnumeration v) {
        value = v;
    }

    public DayTypeEnumeration value() {
        return value;
    }

    public static HolidayTypeEnumerationx fromValue(DayTypeEnumeration v) {
        for (HolidayTypeEnumerationx c: HolidayTypeEnumerationx.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
