/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for Monitoring Service Capability access control
 * 
 * <p>Java class for MonitoringCapabilityAccessControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MonitoringCapabilityAccessControlStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/siri}CapabilityAccessControlStructure">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.siri.org.uk/siri}CheckOperatorRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.siri.org.uk/siri}CheckLineRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.siri.org.uk/siri}CheckMonitoringRef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoringCapabilityAccessControlStructure", namespace = "http://www.siri.org.uk/siri", propOrder = {
    "checkOperatorRef",
    "checkLineRef",
    "checkMonitoringRef"
})
public class MonitoringCapabilityAccessControl
    extends CapabilityAccessControl
{

    @XmlElement(name = "CheckOperatorRef", namespace = "http://www.siri.org.uk/siri", defaultValue = "true")
    protected Boolean checkOperatorRef;
    @XmlElement(name = "CheckLineRef", namespace = "http://www.siri.org.uk/siri", defaultValue = "true")
    protected Boolean checkLineRef;
    @XmlElement(name = "CheckMonitoringRef", namespace = "http://www.siri.org.uk/siri", defaultValue = "true")
    protected Boolean checkMonitoringRef;

    /**
     * Gets the value of the checkOperatorRef property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckOperatorRef() {
        return checkOperatorRef;
    }

    /**
     * Sets the value of the checkOperatorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public MonitoringCapabilityAccessControl setCheckOperatorRef(Boolean value) {
        this.checkOperatorRef = value;
        return this;
    }

    /**
     * Gets the value of the checkLineRef property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckLineRef() {
        return checkLineRef;
    }

    /**
     * Sets the value of the checkLineRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public MonitoringCapabilityAccessControl setCheckLineRef(Boolean value) {
        this.checkLineRef = value;
        return this;
    }

    /**
     * Gets the value of the checkMonitoringRef property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckMonitoringRef() {
        return checkMonitoringRef;
    }

    /**
     * Sets the value of the checkMonitoringRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public MonitoringCapabilityAccessControl setCheckMonitoringRef(Boolean value) {
        this.checkMonitoringRef = value;
        return this;
    }

}
