/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for Visit of a vehicle to a stop monitoring point. May provide information about the arrival, the departure or both.
 * 
 * <p>Java class for MonitoredStopVisitStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MonitoredStopVisitStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/siri}AbstractIdentifiedItemStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.siri.org.uk/siri}StopVisitReferenceGroup" minOccurs="0"/>
 *         &lt;element name="MonitoredVehicleJourney" type="{http://www.siri.org.uk/siri}MonitoredVehicleJourneyStructure"/>
 *         &lt;element name="StopVisitNote" type="{http://www.siri.org.uk/siri}NaturalLanguageStringStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StopFacility" type="{http://www.siri.org.uk/siri}FacilityRefStructure" minOccurs="0"/>
 *         &lt;element ref="{http://www.siri.org.uk/siri}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoredStopVisitStructure", namespace = "http://www.siri.org.uk/siri", propOrder = {
    "monitoringRef",
    "clearDownRef",
    "monitoredVehicleJourney",
    "stopVisitNote",
    "stopFacility",
    "extensions"
})
public class MonitoredStopVisitStructure
    extends AbstractIdentifiedItemStructure
{

    @XmlElement(name = "MonitoringRef", namespace = "http://www.siri.org.uk/siri")
    protected MonitoringRefStructure monitoringRef;
    @XmlElement(name = "ClearDownRef", namespace = "http://www.siri.org.uk/siri")
    protected ClearDownRefStructure clearDownRef;
    @XmlElement(name = "MonitoredVehicleJourney", namespace = "http://www.siri.org.uk/siri", required = true)
    protected MonitoredVehicleJourneyStructure monitoredVehicleJourney;
    @XmlElement(name = "StopVisitNote", namespace = "http://www.siri.org.uk/siri")
    protected List<NaturalLanguageStringStructure> stopVisitNote;
    @XmlElement(name = "StopFacility", namespace = "http://www.siri.org.uk/siri")
    protected FacilityRefStructure stopFacility;
    @XmlElement(name = "Extensions", namespace = "http://www.siri.org.uk/siri")
    protected ExtensionsStructure extensions;

    /**
     * Gets the value of the monitoringRef property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringRefStructure }
     *     
     */
    public MonitoringRefStructure getMonitoringRef() {
        return monitoringRef;
    }

    /**
     * Sets the value of the monitoringRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringRefStructure }
     *     
     */
    public void setMonitoringRef(MonitoringRefStructure value) {
        this.monitoringRef = value;
    }

    /**
     * Gets the value of the clearDownRef property.
     * 
     * @return
     *     possible object is
     *     {@link ClearDownRefStructure }
     *     
     */
    public ClearDownRefStructure getClearDownRef() {
        return clearDownRef;
    }

    /**
     * Sets the value of the clearDownRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearDownRefStructure }
     *     
     */
    public void setClearDownRef(ClearDownRefStructure value) {
        this.clearDownRef = value;
    }

    /**
     * Gets the value of the monitoredVehicleJourney property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoredVehicleJourneyStructure }
     *     
     */
    public MonitoredVehicleJourneyStructure getMonitoredVehicleJourney() {
        return monitoredVehicleJourney;
    }

    /**
     * Sets the value of the monitoredVehicleJourney property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoredVehicleJourneyStructure }
     *     
     */
    public void setMonitoredVehicleJourney(MonitoredVehicleJourneyStructure value) {
        this.monitoredVehicleJourney = value;
    }

    /**
     * Gets the value of the stopVisitNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopVisitNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopVisitNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NaturalLanguageStringStructure }
     * 
     * 
     */
    public List<NaturalLanguageStringStructure> getStopVisitNote() {
        if (stopVisitNote == null) {
            stopVisitNote = new ArrayList<NaturalLanguageStringStructure>();
        }
        return this.stopVisitNote;
    }

    /**
     * Gets the value of the stopFacility property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityRefStructure }
     *     
     */
    public FacilityRefStructure getStopFacility() {
        return stopFacility;
    }

    /**
     * Sets the value of the stopFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityRefStructure }
     *     
     */
    public void setStopFacility(FacilityRefStructure value) {
        this.stopFacility = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsStructure }
     *     
     */
    public ExtensionsStructure getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsStructure }
     *     
     */
    public void setExtensions(ExtensionsStructure value) {
        this.extensions = value;
    }

}
