/*
 * MIT License
 * 
 * Copyright (c) 2020 Hochschule Esslingen
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.org.siri.siri;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import eu.datex2.schema._1_0._1_0.Advice;
import eu.datex2.schema._1_0._1_0.Cause;
import eu.datex2.schema._1_0._1_0.DateTime;
import eu.datex2.schema._1_0._1_0.DatexComment;
import eu.datex2.schema._1_0._1_0.ExtensionType;
import eu.datex2.schema._1_0._1_0.GroupOfLocations;
import eu.datex2.schema._1_0._1_0.Impact;
import eu.datex2.schema._1_0._1_0.InformationUsageEnum;
import eu.datex2.schema._1_0._1_0.Management;
import eu.datex2.schema._1_0._1_0.ProbabilityOfOccurrenceEnum;
import eu.datex2.schema._1_0._1_0.SourceInformation;
import eu.datex2.schema._1_0._1_0.Validity;


import lombok.ToString;
@ToString
/**
 * An event which is not planned by the traffic operator, which is affecting, or has the potential to affect traffic flow. This SIRI-SX element embeds the Datex2 TrafficElement, making all elements optional because  they may alternatvielky be specified by common  SIRI-SRX situation elements
 * 
 * <p>Java class for OptionalTrafficElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OptionalTrafficElementStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.siri.org.uk/siri}Datex2ManagementGroup"/>
 *         &lt;group ref="{http://www.siri.org.uk/siri}Datex2SituationGroup"/>
 *         &lt;group ref="{http://www.siri.org.uk/siri}Datex2RoadGroup"/>
 *         &lt;group ref="{http://www.siri.org.uk/siri}Datex2OtherGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OptionalTrafficElementStructure", namespace = "http://www.siri.org.uk/siri", propOrder = {
    "situationRecordCreationReference",
    "situationRecordCreationTime",
    "situationRecordObservationTime",
    "situationRecordVersion",
    "situationRecordVersionTime",
    "situationRecordFirstSupplierVersionTime",
    "informationUsageOverride",
    "probabilityOfOccurrence",
    "sourceInformation",
    "validity",
    "impact",
    "cause",
    "advice",
    "generalPublicComment",
    "nonGeneralPublicComment",
    "groupOfLocations",
    "management",
    "situationRecordExtension",
    "trafficElementExtension"
})
public abstract class OptionalTrafficElement {

    @XmlElement(namespace = "http://www.siri.org.uk/siri", required = true)
    protected String situationRecordCreationReference;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected DateTime situationRecordCreationTime;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected DateTime situationRecordObservationTime;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger situationRecordVersion;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected DateTime situationRecordVersionTime;
    @XmlElement(namespace = "http://www.siri.org.uk/siri", required = true)
    protected DateTime situationRecordFirstSupplierVersionTime;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    @XmlSchemaType(name = "string")
    protected InformationUsageEnum informationUsageOverride;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    @XmlSchemaType(name = "string")
    protected ProbabilityOfOccurrenceEnum probabilityOfOccurrence;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected SourceInformation sourceInformation;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected Validity validity;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected Impact impact;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected Cause cause;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected List<Advice> advice;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected List<DatexComment> generalPublicComment;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected List<DatexComment> nonGeneralPublicComment;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected GroupOfLocations groupOfLocations;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected Management management;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected ExtensionType situationRecordExtension;
    @XmlElement(namespace = "http://www.siri.org.uk/siri")
    protected ExtensionType trafficElementExtension;

    /**
     * Gets the value of the situationRecordCreationReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSituationRecordCreationReference() {
        return situationRecordCreationReference;
    }

    /**
     * Sets the value of the situationRecordCreationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public OptionalTrafficElement setSituationRecordCreationReference(String value) {
        this.situationRecordCreationReference = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordCreationTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getSituationRecordCreationTime() {
        return situationRecordCreationTime;
    }

    /**
     * Sets the value of the situationRecordCreationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public OptionalTrafficElement setSituationRecordCreationTime(DateTime value) {
        this.situationRecordCreationTime = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordObservationTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getSituationRecordObservationTime() {
        return situationRecordObservationTime;
    }

    /**
     * Sets the value of the situationRecordObservationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public OptionalTrafficElement setSituationRecordObservationTime(DateTime value) {
        this.situationRecordObservationTime = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSituationRecordVersion() {
        return situationRecordVersion;
    }

    /**
     * Sets the value of the situationRecordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public OptionalTrafficElement setSituationRecordVersion(BigInteger value) {
        this.situationRecordVersion = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordVersionTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getSituationRecordVersionTime() {
        return situationRecordVersionTime;
    }

    /**
     * Sets the value of the situationRecordVersionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public OptionalTrafficElement setSituationRecordVersionTime(DateTime value) {
        this.situationRecordVersionTime = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordFirstSupplierVersionTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getSituationRecordFirstSupplierVersionTime() {
        return situationRecordFirstSupplierVersionTime;
    }

    /**
     * Sets the value of the situationRecordFirstSupplierVersionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public OptionalTrafficElement setSituationRecordFirstSupplierVersionTime(DateTime value) {
        this.situationRecordFirstSupplierVersionTime = value;
        return this;
    }

    /**
     * Gets the value of the informationUsageOverride property.
     * 
     * @return
     *     possible object is
     *     {@link InformationUsageEnum }
     *     
     */
    public InformationUsageEnum getInformationUsageOverride() {
        return informationUsageOverride;
    }

    /**
     * Sets the value of the informationUsageOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationUsageEnum }
     *     
     */
    public OptionalTrafficElement setInformationUsageOverride(InformationUsageEnum value) {
        this.informationUsageOverride = value;
        return this;
    }

    /**
     * Gets the value of the probabilityOfOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link ProbabilityOfOccurrenceEnum }
     *     
     */
    public ProbabilityOfOccurrenceEnum getProbabilityOfOccurrence() {
        return probabilityOfOccurrence;
    }

    /**
     * Sets the value of the probabilityOfOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProbabilityOfOccurrenceEnum }
     *     
     */
    public OptionalTrafficElement setProbabilityOfOccurrence(ProbabilityOfOccurrenceEnum value) {
        this.probabilityOfOccurrence = value;
        return this;
    }

    /**
     * Gets the value of the sourceInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SourceInformation }
     *     
     */
    public SourceInformation getSourceInformation() {
        return sourceInformation;
    }

    /**
     * Sets the value of the sourceInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceInformation }
     *     
     */
    public OptionalTrafficElement setSourceInformation(SourceInformation value) {
        this.sourceInformation = value;
        return this;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link Validity }
     *     
     */
    public Validity getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validity }
     *     
     */
    public OptionalTrafficElement setValidity(Validity value) {
        this.validity = value;
        return this;
    }

    /**
     * Gets the value of the impact property.
     * 
     * @return
     *     possible object is
     *     {@link Impact }
     *     
     */
    public Impact getImpact() {
        return impact;
    }

    /**
     * Sets the value of the impact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Impact }
     *     
     */
    public OptionalTrafficElement setImpact(Impact value) {
        this.impact = value;
        return this;
    }

    /**
     * Gets the value of the cause property.
     * 
     * @return
     *     possible object is
     *     {@link Cause }
     *     
     */
    public Cause getCause() {
        return cause;
    }

    /**
     * Sets the value of the cause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cause }
     *     
     */
    public OptionalTrafficElement setCause(Cause value) {
        this.cause = value;
        return this;
    }

    /**
     * Gets the value of the advice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Advice }
     * 
     * 
     */
    public List<Advice> getAdvice() {
        if (advice == null) {
            advice = new ArrayList<Advice>();
        }
        return this.advice;
    }

    /**
     * Gets the value of the generalPublicComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalPublicComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralPublicComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatexComment }
     * 
     * 
     */
    public List<DatexComment> getGeneralPublicComment() {
        if (generalPublicComment == null) {
            generalPublicComment = new ArrayList<DatexComment>();
        }
        return this.generalPublicComment;
    }

    /**
     * Gets the value of the nonGeneralPublicComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonGeneralPublicComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonGeneralPublicComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatexComment }
     * 
     * 
     */
    public List<DatexComment> getNonGeneralPublicComment() {
        if (nonGeneralPublicComment == null) {
            nonGeneralPublicComment = new ArrayList<DatexComment>();
        }
        return this.nonGeneralPublicComment;
    }

    /**
     * Gets the value of the groupOfLocations property.
     * 
     * @return
     *     possible object is
     *     {@link GroupOfLocations }
     *     
     */
    public GroupOfLocations getGroupOfLocations() {
        return groupOfLocations;
    }

    /**
     * Sets the value of the groupOfLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupOfLocations }
     *     
     */
    public OptionalTrafficElement setGroupOfLocations(GroupOfLocations value) {
        this.groupOfLocations = value;
        return this;
    }

    /**
     * Gets the value of the management property.
     * 
     * @return
     *     possible object is
     *     {@link Management }
     *     
     */
    public Management getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     * 
     * @param value
     *     allowed object is
     *     {@link Management }
     *     
     */
    public OptionalTrafficElement setManagement(Management value) {
        this.management = value;
        return this;
    }

    /**
     * Gets the value of the situationRecordExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getSituationRecordExtension() {
        return situationRecordExtension;
    }

    /**
     * Sets the value of the situationRecordExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public OptionalTrafficElement setSituationRecordExtension(ExtensionType value) {
        this.situationRecordExtension = value;
        return this;
    }

    /**
     * Gets the value of the trafficElementExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getTrafficElementExtension() {
        return trafficElementExtension;
    }

    /**
     * Sets the value of the trafficElementExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public OptionalTrafficElement setTrafficElementExtension(ExtensionType value) {
        this.trafficElementExtension = value;
        return this;
    }

}
